version: "3.8"

services: 
  db: 
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: bngoc
      POSTGRES_PASSWORD: '191298'
      POSTGRES_DB: reddit

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8083:8080
    environment: 
      ADMINER_DEFAULT_SERVER: postgres